const SITE_DATA = {
  meta: {
    title: "AI Daily Digest",
    description: "One person's structured daily exploration of artificial intelligence — concepts, news, and business applications explained clearly, built up session by session.",
    author: "Yulia",
    startDate: "March 22, 2026",
  },

  digests: [
    { day: 28, date: "Apr 23, 2026", isoDate: "2026-04-23", title: "KV Cache & World Models", concepts: ["KV Cache", "World Models"], topic: "Architecture", summary: "How AI speeds up inference by caching computation, and how world models let AI plan by simulating outcomes.", useCase: "AI inference cost reduction in production deployments." },
    { day: 27, date: "Apr 22, 2026", isoDate: "2026-04-22", title: "Attention Mechanisms & AI Memory Systems", concepts: ["Attention Mechanisms", "AI Memory Systems"], topic: "Architecture", summary: "How transformers selectively focus on relevant input, and how AI retains information across sessions.", useCase: "Personalised AI assistants that remember user context." },
    { day: 26, date: "Apr 21, 2026", isoDate: "2026-04-21", title: "AI Legal Liability & Benchmarking Limitations", concepts: ["AI Legal Liability", "AI Benchmarking Limitations"], topic: "Governance", summary: "Who is responsible when AI causes harm, and why benchmark scores can be misleading proxies for real capability.", useCase: "Enterprise AI risk and compliance frameworks." },
    { day: 25, date: "Apr 20, 2026", isoDate: "2026-04-20", title: "AI Carbon Footprint & Workforce Displacement", concepts: ["AI Carbon Footprint", "AI Workforce Displacement"], topic: "Governance", summary: "The environmental cost of large model training, and how AI is reshaping job markets across industries.", useCase: "Sustainable AI procurement policies for enterprises." },
    { day: 24, date: "Apr 19, 2026", isoDate: "2026-04-19", title: "AI Compute Scaling Laws & GenAI Paradox", concepts: ["AI Compute Scaling Laws", "GenAI Paradox"], topic: "Business", summary: "Empirical rules governing how AI capability scales with compute, and the gap between AI hype and measurable ROI.", useCase: "Budgeting AI infrastructure investment for diminishing returns." },
    { day: 23, date: "Apr 18, 2026", isoDate: "2026-04-18", title: "Multi-Agent Systems & Edge AI", concepts: ["Multi-Agent Systems", "Edge AI"], topic: "Architecture", summary: "Networks of collaborating AI agents tackling complex tasks, and AI running locally on-device without cloud.", useCase: "Autonomous supply chain orchestration." },
    { day: 22, date: "Apr 17, 2026", isoDate: "2026-04-17", title: "AI Safety vs Ethics & Guardrails", concepts: ["AI Safety vs AI Ethics", "Guardrails"], topic: "Safety", summary: "The distinction between making AI reliably safe and making AI morally aligned, plus the filters that enforce constraints.", useCase: "Building compliant AI products for regulated industries." },
    { day: 21, date: "Apr 16, 2026", isoDate: "2026-04-16", title: "Embedding Models & Federated Learning", concepts: ["Embedding Models", "Federated Learning"], topic: "Infrastructure", summary: "Converting language into mathematical vectors that capture meaning, and training AI across devices without sharing raw data.", useCase: "Privacy-preserving AI in healthcare and finance." },
    { day: 20, date: "Apr 15, 2026", isoDate: "2026-04-15", title: "AI Inference Infrastructure & Knowledge Distillation", concepts: ["AI Inference Infrastructure", "Knowledge Distillation"], topic: "Infrastructure", summary: "The hardware and software stack that serves AI at scale, and shrinking large models into smaller, deployable ones.", useCase: "Reducing model serving costs at enterprise scale." },
    { day: 19, date: "Apr 14, 2026", isoDate: "2026-04-14", title: "AI Safety Evaluations & Prompt Injection", concepts: ["AI Safety Evaluations", "Prompt Injection"], topic: "Safety", summary: "Structured red-teaming tests for AI safety, and attacks that hijack AI behaviour via hidden instructions.", useCase: "Security testing for AI-powered customer-facing products." },
    { day: 18, date: "Apr 13, 2026", isoDate: "2026-04-13", title: "Agentic Commerce & Neuro-Symbolic AI", concepts: ["Agentic Commerce", "Neuro-Symbolic AI"], topic: "Architecture", summary: "AI agents that autonomously buy, book, and transact on your behalf, combined with symbolic reasoning for logic.", useCase: "AI-driven procurement automation in B2B." },
    { day: 17, date: "Apr 12, 2026", isoDate: "2026-04-12", title: "AI Observability & Vibe Coding", concepts: ["AI Observability", "Vibe Coding"], topic: "Business", summary: "Monitoring AI in production to catch errors, and building software by describing intent in plain language.", useCase: "Internal tooling built by non-engineers using AI." },
    { day: 16, date: "Apr 11, 2026", isoDate: "2026-04-11", title: "Test-Time Compute & Quantization", concepts: ["Test-Time Compute", "Quantization"], topic: "Infrastructure", summary: "Giving AI more thinking time per query to improve reasoning, and compressing models to run cheaper.", useCase: "Cost-quality trade-offs in AI product deployment." },
    { day: 15, date: "Apr 10, 2026", isoDate: "2026-04-10", title: "Mixture of Experts & AI Sovereignty", concepts: ["Mixture of Experts", "AI Sovereignty"], topic: "Governance", summary: "Routing queries to specialised model sub-networks for efficiency, and national strategies for AI independence.", useCase: "Evaluating AI vendor lock-in risk for enterprises." },
    { day: 14, date: "Apr 9, 2026", isoDate: "2026-04-09", title: "Physical AI & Transformer Architecture", concepts: ["Physical AI", "Transformer Architecture"], topic: "Architecture", summary: "AI that controls robots and physical systems, and the attention-based neural network design behind all modern LLMs.", useCase: "AI-guided quality inspection in manufacturing." },
    { day: 13, date: "Apr 8, 2026", isoDate: "2026-04-08", title: "Small Language Models & Synthetic Data", concepts: ["Small Language Models", "Synthetic Data"], topic: "Models", summary: "Compact models that run on-device without cloud, and artificially generated data for training AI when real data is scarce.", useCase: "On-device AI for enterprise mobile apps." },
    { day: 12, date: "Apr 7, 2026", isoDate: "2026-04-07", title: "AI Alignment & Vector Search", concepts: ["AI Alignment", "Vector Search"], topic: "Safety", summary: "Ensuring AI does what humans actually intend, and finding information by meaning rather than keywords.", useCase: "Semantic product search in e-commerce." },
    { day: 11, date: "Apr 6, 2026", isoDate: "2026-04-06", title: "Hallucination & RLHF", concepts: ["Hallucination", "RLHF"], topic: "Safety", summary: "When AI confidently makes up wrong information, and using human feedback to steer models toward better behaviour.", useCase: "Human-in-the-loop review for AI-generated content." },
    { day: 10, date: "Apr 5, 2026", isoDate: "2026-04-05", title: "Digital Twins & GEO", concepts: ["Digital Twins", "GEO"], topic: "Business", summary: "Virtual replicas of physical systems for safe AI testing, and optimising content to be cited by AI instead of search engines.", useCase: "Content strategy for the AI-answer era." },
    { day: 9, date: "Apr 4, 2026", isoDate: "2026-04-04", title: "MCP & Explainable AI", concepts: ["MCP", "Explainable AI"], topic: "Infrastructure", summary: "The universal protocol connecting AI agents to external tools, and making AI decision-making transparent.", useCase: "Explainability requirements for AI in financial services." },
    { day: 8, date: "Apr 3, 2026", isoDate: "2026-04-03", title: "Open Source AI & RAG", concepts: ["Open Source AI", "RAG"], topic: "Infrastructure", summary: "Publicly available model weights anyone can run or modify, and connecting AI to live external knowledge at query time.", useCase: "Building internal knowledge bases with RAG." },
    { day: 7, date: "Apr 2, 2026", isoDate: "2026-04-02", title: "Prompt Engineering & Fine-Tuning", concepts: ["Prompt Engineering", "Fine-Tuning"], topic: "Models", summary: "The craft of writing inputs that reliably get better AI outputs, and training pre-built models further on specialist data.", useCase: "Customising AI for legal document drafting." },
    { day: 6, date: "Apr 1, 2026", isoDate: "2026-04-01", title: "Tokens & Benchmarks", concepts: ["Tokens", "Benchmarks"], topic: "Models", summary: "The text chunks AI actually processes as its unit of currency, and standardised tests for comparing model performance.", useCase: "Evaluating AI vendors using benchmark literacy." },
    { day: 5, date: "Mar 31, 2026", isoDate: "2026-03-31", title: "Multimodal AI & Context Windows", concepts: ["Multimodal AI", "Context Windows"], topic: "Models", summary: "AI that handles text, images, and audio simultaneously, and how much content a model can 'see' at once.", useCase: "AI-powered document understanding for back-office automation." },
    { day: 4, date: "Mar 30, 2026", isoDate: "2026-03-30", title: "AI Inference & Agents", concepts: ["Inference", "AI Agents"], topic: "Architecture", summary: "When a trained model runs and produces output, and AI systems that autonomously take actions toward goals.", useCase: "Automating multi-step research workflows with AI agents." },
    { day: 3, date: "Mar 29, 2026", isoDate: "2026-03-29", title: "Training Data & Parameters", concepts: ["Training Data", "Parameters"], topic: "Models", summary: "The datasets AI learns from and why data quality matters, plus the millions of numerical values that form a model's memory.", useCase: "Data strategy as a competitive advantage in AI." },
    { day: 2, date: "Mar 28, 2026", isoDate: "2026-03-28", title: "Neural Networks & LLMs", concepts: ["Neural Networks", "LLMs"], topic: "Architecture", summary: "Layers of mathematical functions loosely inspired by the brain, and the large-scale language models built on top of them.", useCase: "Evaluating LLM providers for enterprise deployment." },
    { day: 1, date: "Mar 22, 2026", isoDate: "2026-03-22", title: "AI vs Machine Learning", concepts: ["AI", "Machine Learning"], topic: "Models", summary: "The broad concept of machine intelligence and where ML fits within it as the data-driven learning subset.", useCase: "Framing AI strategy conversations with leadership." },
  ],

  glossary: [
    { term: "AI Agents", def: "AI systems that take autonomous actions toward goals, not just answer questions.", day: 4 },
    { term: "AI Alignment", def: "Ensuring AI systems do what humans actually intend, not just what they're literally told.", day: 12 },
    { term: "AI Benchmarking Limitations", def: "Why benchmark scores can be misleading proxies for real-world AI capability.", day: 26 },
    { term: "AI Carbon Footprint", def: "The energy and environmental cost of training and running large AI models.", day: 25 },
    { term: "AI Compute Scaling Laws", def: "Empirical rules describing how AI capability grows with compute, data, and model size.", day: 24 },
    { term: "AI Legal Liability", def: "The unsettled question of who is legally responsible when AI causes harm or makes errors.", day: 26 },
    { term: "AI Memory Systems", def: "Mechanisms that let AI models retain and retrieve information across sessions and conversations.", day: 27 },
    { term: "AI Observability", def: "Monitoring AI behaviour in production to catch drift, errors, and unexpected outputs.", day: 17 },
    { term: "AI Safety Evaluations", def: "Structured red-teaming and testing to measure whether AI systems behave safely under pressure.", day: 19 },
    { term: "AI Safety vs AI Ethics", def: "Safety focuses on reliable, controllable AI behaviour; ethics focuses on moral alignment and fairness.", day: 22 },
    { term: "AI Sovereignty", def: "A nation's ability to develop, control, and sustain AI capabilities independently.", day: 15 },
    { term: "AI Workforce Displacement", def: "How AI automation reshapes job markets, eliminating some roles while creating others.", day: 25 },
    { term: "Agentic Commerce", def: "AI agents that autonomously conduct transactions — buying, booking, procuring — on behalf of users.", day: 18 },
    { term: "Attention Mechanisms", def: "How transformer models selectively weight and focus on the most relevant parts of their input.", day: 27 },
    { term: "Benchmarks", def: "Standardised tests used to measure and compare AI model performance across tasks.", day: 6 },
    { term: "Context Windows", def: "The maximum amount of text an AI model can 'see' and work with in a single interaction.", day: 5 },
    { term: "Digital Twins", def: "Virtual replicas of real-world systems used to safely train and test AI before deployment.", day: 10 },
    { term: "Edge AI", def: "Running AI models directly on local devices rather than in remote cloud infrastructure.", day: 23 },
    { term: "Embedding Models", def: "Models that convert text or other data into numerical vectors that capture semantic meaning.", day: 21 },
    { term: "Explainable AI (XAI)", def: "Techniques that make AI decision-making transparent and interpretable to humans.", day: 9 },
    { term: "Federated Learning", def: "Training AI models across many devices without centralising or sharing raw data.", day: 21 },
    { term: "Fine-Tuning", def: "Taking a pre-trained model and training it further on specific, domain-relevant data.", day: 7 },
    { term: "GEO", def: "Generative Engine Optimisation — creating content designed to be cited by AI models, not just ranked by search.", day: 10 },
    { term: "GenAI Paradox", def: "The gap between widespread GenAI adoption enthusiasm and measurable, hard business ROI.", day: 24 },
    { term: "Guardrails", def: "Rules, filters, and constraints that limit AI outputs to safe, appropriate, and policy-compliant responses.", day: 22 },
    { term: "Hallucination", def: "When an AI model confidently generates factually wrong or entirely made-up information.", day: 11 },
    { term: "Inference", def: "The process of a trained AI model actually running and producing outputs in response to inputs.", day: 4 },
    { term: "KV Cache", def: "A memory optimisation that stores previously computed attention key-value pairs to dramatically speed up inference.", day: 28 },
    { term: "Knowledge Distillation", def: "Training a smaller, faster student model to mimic the outputs of a larger, more capable teacher model.", day: 20 },
    { term: "LLMs", def: "Large Language Models — AI trained on massive text corpora to understand and generate human language.", day: 2 },
    { term: "MCP", def: "Model Context Protocol — a universal open standard connecting AI agents to external tools and data sources.", day: 9 },
    { term: "Machine Learning", def: "The subset of AI where systems learn patterns from data rather than following explicit rules.", day: 1 },
    { term: "Mixture of Experts", def: "A model architecture that routes each query to specialised sub-networks for improved efficiency at scale.", day: 15 },
    { term: "Multi-Agent Systems", def: "Networks of individual AI agents that collaborate, communicate, and divide tasks to complete complex goals.", day: 23 },
    { term: "Multimodal AI", def: "AI systems that process and generate across multiple data types — text, images, audio, video — simultaneously.", day: 5 },
    { term: "Neural Networks", def: "Layers of interconnected mathematical functions loosely inspired by the structure of the human brain.", day: 2 },
    { term: "Neuro-Symbolic AI", def: "Combining statistical neural networks with rule-based symbolic reasoning for stronger logical capabilities.", day: 18 },
    { term: "Open Source AI", def: "AI models whose weights are publicly released, allowing anyone to run, modify, or build on them.", day: 8 },
    { term: "Parameters", def: "The numerical values a model adjusts during training — the encoded 'memory' of what it has learned.", day: 3 },
    { term: "Physical AI", def: "AI that operates in and actively controls real physical systems — robots, vehicles, industrial machinery.", day: 14 },
    { term: "Prompt Engineering", def: "The discipline of crafting AI inputs to reliably elicit higher-quality, more accurate outputs.", day: 7 },
    { term: "Prompt Injection", def: "Attacks that hijack AI behaviour by embedding malicious instructions in content the model processes.", day: 19 },
    { term: "Quantization", def: "Reducing the numerical precision of model weights to compress AI and run it faster with minimal quality loss.", day: 16 },
    { term: "RAG", def: "Retrieval-Augmented Generation — connecting AI to external, up-to-date knowledge sources at query time.", day: 8 },
    { term: "RLHF", def: "Reinforcement Learning from Human Feedback — using human preference ratings to steer models toward better outputs.", day: 11 },
    { term: "Small Language Models", def: "Compact, efficient AI models deployable on-device without cloud infrastructure.", day: 13 },
    { term: "Synthetic Data", def: "Artificially generated data that mimics real-world data, used to train AI when real data is scarce or sensitive.", day: 13 },
    { term: "Test-Time Compute", def: "Allocating extra processing time at inference — letting AI 'think longer' to improve output quality.", day: 16 },
    { term: "Tokens", def: "The sub-word chunks that AI models actually process — the fundamental unit of language model computation.", day: 6 },
    { term: "Training Data", def: "The datasets an AI model learns from — quality, diversity, and volume directly shape model capability.", day: 3 },
    { term: "Transformer Architecture", def: "The attention-based neural network design that underpins virtually all modern large language models.", day: 14 },
    { term: "Vector Search", def: "Finding relevant results by comparing semantic meaning in vector space, not exact keyword matching.", day: 12 },
    { term: "Vibe Coding", def: "Building software by describing intent in plain language and letting AI write the implementation.", day: 17 },
    { term: "World Models", def: "AI systems that build internal simulations of how the world works, enabling planning and forward prediction.", day: 28 },
  ],

  topics: ["Architecture", "Business", "Governance", "Infrastructure", "Models", "Safety"],
};
